# khi thêm cái gì nhớ chạy lại lệnh sau ở terminal: docker compose up -d
services:
  postgres:
    image: postgres:16
    container_name: clean_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clean_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    container_name: clean_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
